{ pkgs, ... }: {
  homebrew = {
    enable = true;
    casks = [
      "telegram-desktop"
      "vagrant"
      "godot"
      "steam"
      "godot-mono"
      "openscad"
      "yacreader"
      "caffeine"
      "alfred"
      "blender"
      "mars"
      "raycast"
      "rustrover"
      "joplin"
      "logisim-evolution"
      "vagrant-vmware-utility"
      "lagrange"
      "qtspim"
      "citra"
      "firefox"
      "mpv"
      "openlens"
      "nvidia-geforce-now"
      "shortcat"
      "xournal-plus-plus"
      "transmission"
      "rectangle"
      "logi-options-plus"
      "vlc"
      "mattermost"
      "balenaetcher"
      "cyberduck"
      "syncthing"
      "zotero"
      "vmware-fusion"
      "gimp"
      "chromium"
      "element"
      "iterm2"
      "mumble"
      "koodo-reader"
      "insomnia"
      "bruno"
      "android-platform-tools"
      "slack"
      "blackhole-64ch"
      "notion"
      "bambu-studio"
      "airflow"
      "mumble"
      "soulseek"
      "tunnelblick"
      "syncplay"
      "anydesk"
      "obsidian"
      "intellij-idea-ce"
      "utm"
      "chiaki"
      "logseq"
      "karabiner-elements"
      "vscodium"
      "webstorm"
      "thunderbird"
      "whatsapp"
    ];
    brews = [
      "qemu"
      "wimlib"
      "spice-protocol"
      "podman"
      "wakeonlan"
      "platformio"
      "alpine"
      "esphome"
      "qt"
      "magic-wormhole"
      "k6"
      "mongodb-atlas-cli"
      "minidlna"
    ];
    taps = [{
      name = "null-dev/firefox-profile-switcher";
      clone_target = "https://github.com/null-dev/firefox-profile-switcher";
      force_auto_update = true;
    }];
  };
}
