{
  lib,
  buildNpmPackage,
  fetchzip,
  nodejs_22,
  python3,
}:

buildNpmPackage rec {
  pname = "openwiki";
  version = "0.3.1";

  nodejs = nodejs_22; # package.json engines: node >= 22

  src = fetchzip {
    url = "https://registry.npmjs.org/openwiki/-/openwiki-${version}.tgz";
    hash = "sha256-b7dRterO37ylf/odAEX1q2UO5hKXmCM0hiLLZpENafs=";
  };

  npmDepsHash = "sha256-rDCdoRug+F8QecaCRsitxpWPhM2lYtOJdwBQ/6kEyys=";

  # The npm tarball ships a prebuilt ./dist but no lock file, and its manifest
  # carries devDependencies that a runtime-only lock cannot satisfy. Both files
  # are generated by ./update.sh; plain `cp` only, because these phases also run
  # in the fixed-output npm-deps derivation, which has no extra build inputs.
  postPatch = ''
    cp ${./package.json} package.json
    cp ${./package-lock.json} package-lock.json
  '';

  # better-sqlite3 (via @langchain/langgraph-checkpoint-sqlite) is a native
  # module and must be compiled from its bundled sources.
  nativeBuildInputs = [
    python3
  ];

  # deepagents pins langsmith ^0.7.1 while openwiki wants ^0.8.3; upstream
  # builds with pnpm, which tolerates that. npm needs to be told to.
  npmFlags = [ "--legacy-peer-deps" ];

  dontNpmBuild = true;

  # Keep the compiled better-sqlite3 addon, drop ~25M of node-gyp leftovers.
  postInstall = ''
    bs=$out/lib/node_modules/openwiki/node_modules/better-sqlite3
    find $bs/build -mindepth 1 -maxdepth 1 ! -name Release -exec rm -rf {} +
    rm -rf $bs/build/Release/obj $bs/build/Release/obj.target \
      $bs/build/Release/sqlite3.a $bs/build/Release/test_extension.node \
      $bs/deps $bs/src
  '';

  meta = {
    description = "CLI that writes and maintains agent documentation for your codebase";
    homepage = "https://github.com/langchain-ai/openwiki";
    downloadPage = "https://www.npmjs.com/package/openwiki";
    license = lib.licenses.mit;
    mainProgram = "openwiki";
    platforms = lib.platforms.unix;
  };

  passthru.updateScript = ./update.sh;
}
