---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-openobserve
  namespace: garage
spec:
  encryptedData:
    accessKey: AgBHHeVCKTXjPxszl4nbI/mrAwLcTBKMjddXk8FY/Fp8sbYuvoZGfR/WAo3mJfwh68ohygSY2qrbvI3nyvoAOJqre9NkZxMK/QUTpnUCrK4tucC1vwRQBYeuh6z/keP9Mjqx+F6ZCVNqgTzZNXXe+QWU+cSDSSRVmkTJcad3BdNk1ChFQvkpVjVrmw66myP/tnGK0znfaiHXKBRh4CHvjqxkVZb4YGffdX0RYwLga58AAWDZYk9rkaTNWm+29RkKT6l43goIvmwfsdRHtAzpd5cyjyR1RY6Ti4+BrqlHvd41dysjmwrv9smp2yF20ypUb6ejDh+CyFhebl52P90ja9W9EF0mWtt7Jg/mbv6YE2x3uxT0XFacymyrPlGsotF7JNgdpdj3bQpGl50h5uLtNOzSwfnrOdfH1N11r7pGfTSrxOo9vNlKoEl4bHR+SoKihTujowV0HdesLMpcYWaGms7Obn8o+0EmUDybfHTboQ10cPan1pthOTbxxbbAorAc0G/RyrJLQH8JqytgOrAd1WkdCCKGhx6mzgAWYUMV2k6PzQkvtAx+YeJR9yzDK+kd+2NYd+HV7Eyzm790T/wNQxY/6Yq14s99UDCovFOv9/JqgpEx0qT7HMPTVf41q2tLWD6+biKZfzEDyoViBRZlPmQkO5Pnru2tCGhVNZH+dZiqWhxRXVcPIQO5g+J5UVsptx3VHwSZeeISH4YtUuUSWWOJk71OfCqNSADooQ==
    secretKey: AgCW25ZTpAX0h178ZG5q+N2ok71j88+Loq2D5XfvpKWOv0dmRGNaKqjEcgbzCkN3XIRiMJeRcJXO14D+Zg2jGD9PdH7ucs5Wq4NyiQxVLfPz5f5ZNMupOta0OBnNsI8OEPz0xeTiw7+QrFe8B4Ss3kg36CrLPYOolXDbmFEAz8HmmUJCYHwZ8rE1WezgYavk65Zibhzy43UfrWsAA1sM/Xqga4ddW7JpHo9FbO+R2XvSk0QMhoWA9xDPURd6WZVtY0+xg4Jnn2c6tX+4kUIGF3/qhcY3wkmkL/IvYfgjr+b2OfwY/1Qk1qQPb6YdrXoCa0yXnSBg7Z/duavOBvaeaejYUkIXvE/sAn4a3JTdDvwVH4dQ/EqKkSt5+eoAWkrW5vPU52J4nLX049paWmnYVAupk7TWKDxYYCNJH6WEmhuHmUudv3Eea7ZpVAsOztmCZ7jefeXR2pCroCX7zGp8zO+dTyZ0dJkRH+Objwrh8NQMP10BgvzwDPQ7IJmihBVHQ11KzPD5VCW4ZdpRZtvMTLArXUcPWjEDz8LSFr5Q6tybmOkx2iADGBeM6qbY25RD+Sxelm1L1PzKmJHfLGTpECeXlXfsqe6ECDK7vLFmB7vFk8tB475DdhjpIj0IfbzZY8gzEvnZAoHnJOygnDwK4qrbslOMfsZV0PFze++AJzL2KlrT0VX1eYHOxJpod3iKuz7xg1xrzgbHnjapU7BLs7DczD5/mY6uz6vPX6JtOWEr2b6qvY0YfOlVslVZnvJnX+qFnZRZZhnYxJLKkRk8Oiyy
  template:
    metadata:
      name: garage-openobserve
      namespace: garage
