---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-openobserve
  namespace: garage
spec:
  encryptedData:
    accessKey: AgChpjuMCGbKdY83FY1UG9C6ZxaC2w57pe22ORH9UKBWp55DoWi1ErbCGq7rzkXJE8a9mhacF1UjiW9aO0MgHzBYM9CClUX+HK/JSdrAC8Ur4GLRfeupC33cb1Zi3uAHAE2NnIhoYWWTMPQ5dzVsZLqYNSON6rxXwaBbAtd7v1L6YBRsNz56FeNRjV3pAZ7S71GYq1jzI4WszERsYNLqVSn79tw+5p37yjvyFfNNrkWVndC2Xu/xMWOwmc7nI6Ex9Q5rtIidkfUJoflbTwbZmyge4e3JQjAaRJyozmpsDcPV6Al+19opcW3GXXFSJzaifLI2lic4slUxNIBYx/Th/+Ry1I9OTl2ookaqcSF79sYUiQc2Voljf00HXfbNlt2qW4TVltPb5V+6Xlg0hOGzaY98kAtKlIBFj/C4iOVWRggF8Uh9YOMmrPfWbpIjeXJfR4LMARxtc8Bu1f+MAuJ1rVYxKXnNT969TIX1NH0na2QYfg1GKHtazFlMmFY4EGhtagiiBw6hZlmHHPqdxqO7qcq7Ha5YZRRL1i7dDceo/s5c6L1rd6PK5RWqOeTJkmVIBDBIonwrpr38AK+EucTbl8lOdnEfhRZNrjVhZw9DEeLI66EEQKo8GeD99bwwv3nUDUlb16yO8PQwd7+CSYT8EWIm4GdjGtKxBK4nWHejCsKriwi0DMJ21FQZkAAPTmoV3lkZ/zDKzBZ8qaQYfPkeg4A8vAT8vnZosHqy8TunZStY8qYn
    secretKey: AgALfzoRcDvY9SiqUlRSsP29QPbumb0NW1ni2LFiqjfm+gb3fjZHajoOD8mTcxmU4XZYnkVEeHOp54Uym1mUdU1I5O96UrfCmQWP7Kd/zkjo3+KgAjVGjjdk58qNwpKEt0Gyytf245OrvEcQizzjuyjS1cIyg5nGfoSPo082+4WX3r3Z4ZNwRQFhIUuqvOYylJGm9TWqaQoNMGhH3a6D21moBrP6+L4Vg9q7h+VHF46n2gOyJIyG0TjQG4SXuY2CAu7/73e21IAmZBWM9HrVweQWfFJGu1bMuTaaSNuQEvk0FJ54H8Mc04CAWXM6h3YF7CKrXv2O5D0xwo/6YcUWvjpFs0YNJoyOaUJ+Fypqto28Cs+xbSnWxZvnUl9pCLVTsdeEfo648FKsyFPD6WPs+0XZBHgrI5W5MVmHQkgngFfI++NEXVcd9KWJbp0ocLP9rgLWpPEUmWUXLsAwnv3/xytGWw3bXWOVLfbVwQG1p/fKHOccceGW9O31iuSe0E0mrZu8RPm95XxFT2gdgx6qixtPxnfVWOgIMdc2dCE0evLgXytQ+FqSOiKC+lcxS8tJcC/xVl+pT4+lKK2aMLIs6x7DV1ZTW+ycUCyzoD2A/bFWxX8aeDe/gphjM9soJSnJHwNgZ2kkJ8QlUeXWCgvCgi1IOxcvZ16D71dwrnIRVo/2YRK7qg3to6PufUoUM6YTUJ4eHVUmKPHVlHkWuhUzPV8ar+UUUKgTQLPcsBme+zhrMLTz1UFTS1tBjr+3AtkRT0FdSgMvxu0XM0IpEKWQSi0w
  template:
    metadata:
      name: garage-openobserve
      namespace: garage
    type: Opaque
