keys:
  - &server_zima age1ggaagfgxr59gxcmstcc8vpvenz7jflz4de3tj23ek0gf869av5eq45atmr
  - &server_hermes age108fdgns3fg4eldggstagplguxacqnwn5k4yh2s3y384ax9srmvmqqd45ld
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *server_zima
      - *server_hermes
  - path_regex: \.yaml$
    key_groups:
    - age:
      - *server_zima
      - *server_hermes
