apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  targetNamespace: cnpg-system
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.29.0 <0.30.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 1h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
  ref:
    semver: ">=1.6.1 <2.0.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  targetNamespace: dragonfly-operator-system
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://bitnami.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  targetNamespace: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: ">=2.19.3 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 1h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
