apiVersion: v1
kind: ServiceAccount
metadata:
  name: openobserve-collector
  namespace: openobserve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openobserve-collector
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - pods
    verbs: [get, list, watch]
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openobserve-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openobserve-collector
subjects:
  - kind: ServiceAccount
    name: openobserve-collector
    namespace: openobserve
