apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-data
  namespace: openobserve
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
